### ISSUE TITLE
bas2tap - Capital keyword conversion problems

### ISSUE THREAD

**Issue by plirof** [zxplay/zxplay#1]
Again thanks for a very good job! 

I'm re-posting here the same issue (I hope it helps better)!
"I noticed that the converter have some issues with capital letters. eg it does not consider "print" or "Print" spectrum commands. This might make it less appealing to begginers. In my version I use zmakebas which seems (to me) a bit more forgiving... 
In the beggining I started also with bas2tap but because of these type of problems I switched to zmakebas." . I'm not sure if zmakebas is actually better than bas2tap but it does what I want.

My repo is here : https://github.com/gamesedu/zx_htm2tap

**Comment by stever** [comment]
@plirof I have replaced bas2tap with [zmakebas](https://github.com/zxplay/zmakebas).

Tested with [demo.bas](https://raw.githubusercontent.com/zxplay/zmakebas/master/docs/demo.bas). There is an option that doesn't require line numbers and allows labels. I haven't added that option so far.

**Comment by plirof** [comment]
I was aiming for pure Sinclair Basic (for educational purposes) so Labels are not important for me!
Very good job :)
