### ISSUE TITLE
Feature suggestion : Maybe add a 3rd tab for Boriel ZXBasic 

### ISSUE THREAD

**Issue by plirof** [zxplay/zxplay#2]
I'm not really interested in anything more than pure Sinclair Basic and you've already done that from step 1 :)
I was thinking that -since you have done all the difficult job- you could also add a tab for Boriel ZXBasic :)
I believe many developers pro & amateurs with be interested in that!
Have Fun :)

**Comment by stever** [comment]
Thanks for the suggestion. Boriel ZX Basic is great. I have now integrated this.
