### ISSUE TITLE
Legacy release without wasm (-s WASM=0)

### ISSUE THREAD

**Issue by plirof** [zxplay/zxplay#3]
This is kind of personal request - I don't think other people might benefit much from this.

One on the labs I use uses very old browsers (used also for flash support) and can't run wasm. 
Is it possible to add a vanilla JS release? 
I tried changing package.json and adding -s WASM in various places but it didn't seem to work. (https://emscripten.org/docs/getting_started/FAQ.html#what-is-no-webassembly-support-found-build-with-s-wasm-0-to-target-javascript-instead-or-no-native-wasm-support-detected )

Another option I have is to use a vanilla JS version of zmakebas but I couldn't use that also...
Thanks :)
(edit)I think this parameter can be entered only during zmakebas creation - JSSPeccy do not use emscripten. So I guess my first option (whole zxplay compiled as vanilla JS is not easy... (/edit)

**Comment by stever** [comment]
Closing this issue as I won't be investigating a non-WASM alternative. There will be more WASM besides JSSpeccy3. It would be too limiting (and also no time) to attempt to support this directly.
